-- FITTO 초기 스키마 (설계서 v2.0 — 5. DB 설계)
-- 관계(relations) 기반 구조 + 트레이너 테이블. 총 8개 테이블.

-- 5.2 users (회원)
CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             VARCHAR(255) NOT NULL UNIQUE,
    password          VARCHAR(255),
    name              VARCHAR(50)  NOT NULL,
    birth_date        DATE,
    gender            VARCHAR(10),
    profile_image_url VARCHAR(500),
    role              VARCHAR(20)  NOT NULL DEFAULT 'USER',  -- USER / TRAINER / ADMIN
    social_type       VARCHAR(20),                           -- KAKAO / APPLE / EMAIL
    social_id         VARCHAR(255),
    created_at        TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- 5.3 relations (관계) — COUPLE / TRAINER_MEMBER
CREATE TABLE relations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_type   VARCHAR(30) NOT NULL,                    -- COUPLE / TRAINER_MEMBER
    user_a_id       BIGINT      NOT NULL REFERENCES users (id),
    user_b_id       BIGINT      REFERENCES users (id),       -- 연결 전 NULL
    invite_code     VARCHAR(10) UNIQUE,
    code_expires_at TIMESTAMP,
    status          VARCHAR(20) NOT NULL,                    -- PENDING / ACTIVE / ENDED
    connected_at    TIMESTAMP,
    ended_at        TIMESTAMP,
    created_at      TIMESTAMP   NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_relations_user_a ON relations (user_a_id);
CREATE INDEX idx_relations_user_b ON relations (user_b_id);

-- 5.4 trainer_profiles (트레이너 프로필)
CREATE TABLE trainer_profiles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL UNIQUE REFERENCES users (id),
    specialty    VARCHAR(100),
    introduction TEXT,
    career       TEXT,
    certificate  VARCHAR(500),
    max_members  INT          NOT NULL DEFAULT 10,
    is_accepting BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- 5.5 workouts (운동 기록)
CREATE TABLE workouts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL REFERENCES users (id),
    relation_id        BIGINT REFERENCES relations (id),     -- 트레이너 루틴 기반 시
    workout_date       DATE   NOT NULL,
    total_duration_min INT,
    memo               TEXT,
    created_at         TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_workouts_user_date ON workouts (user_id, workout_date);

-- 5.6 workout_sets (운동 세트)
CREATE TABLE workout_sets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id    BIGINT       NOT NULL REFERENCES workouts (id) ON DELETE CASCADE,
    exercise_name VARCHAR(100) NOT NULL,
    category      VARCHAR(50),
    sets          INT,
    reps          INT,
    weight_kg     DECIMAL(5, 2),
    order_no      INT          NOT NULL DEFAULT 1
);
CREATE INDEX idx_workout_sets_workout ON workout_sets (workout_id);

-- 5.7 trainer_routines (트레이너 루틴)
CREATE TABLE trainer_routines (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id  BIGINT       NOT NULL REFERENCES relations (id),
    trainer_id   BIGINT       NOT NULL REFERENCES users (id),
    member_id    BIGINT       NOT NULL REFERENCES users (id),
    title        VARCHAR(100) NOT NULL,
    description  TEXT,
    routine_date DATE,
    is_completed BOOLEAN      NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMP,
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_trainer_routines_relation ON trainer_routines (relation_id);

-- 5.8 chat_messages (채팅 메시지)
CREATE TABLE chat_messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id  BIGINT      NOT NULL REFERENCES relations (id),
    sender_id    BIGINT      NOT NULL REFERENCES users (id),
    message_type VARCHAR(20) NOT NULL,                       -- TEXT / IMAGE / WORKOUT_CARD / ROUTINE_CARD
    content      TEXT,
    image_url    VARCHAR(500),
    workout_id   BIGINT      REFERENCES workouts (id),
    routine_id   BIGINT      REFERENCES trainer_routines (id),
    is_read      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP   NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_chat_messages_relation ON chat_messages (relation_id, created_at);

-- 5.9 streaks (스트릭)
CREATE TABLE streaks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      REFERENCES users (id),     -- 개인 스트릭
    relation_id       BIGINT      REFERENCES relations (id), -- 커플 공동 스트릭
    streak_type       VARCHAR(20) NOT NULL,                  -- PERSONAL / COUPLE
    current_count     INT         NOT NULL DEFAULT 0,
    max_count         INT         NOT NULL DEFAULT 0,
    last_workout_date DATE,
    updated_at        TIMESTAMP   NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_streaks_user ON streaks (user_id);
CREATE INDEX idx_streaks_relation ON streaks (relation_id);
