-- 푸시 디바이스 토큰 (Expo Push) — 설계서 CHAT-06
CREATE TABLE device_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id),
    token      VARCHAR(255) NOT NULL UNIQUE,
    platform   VARCHAR(20),
    created_at TIMESTAMP    NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_device_tokens_user ON device_tokens (user_id);
