-- 식단 기록 (meals) — 끼니별 사진/메모/칼로리
CREATE TABLE meals (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id),
    meal_date  DATE        NOT NULL,
    meal_type  VARCHAR(20) NOT NULL,          -- BREAKFAST / LUNCH / DINNER / SNACK
    memo       TEXT,
    photo_url  TEXT,
    calories   INT,
    created_at TIMESTAMP   NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_meals_user_date ON meals (user_id, meal_date);
